name: Backup VPS ke HuggingFace Bucket

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Install depedencies
        run: |
            apt-get install -y rclone
            apt-get install -y mysql-client
            apt-get install -y default-mysql-client
            apt-get install -y sshpass
