name: Backup VPS ke HuggingFace Bucket

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Install depedencies
        run: |
            pip install modal
